services:
  flask-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/Escuela
    links:
      - mongodb
    depends_on:
      - mongodb
      

  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - mongo_data_api:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_DATABASE: Escuela
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root 

volumes:
  mongo_data_api: